### ISSUE TITLE
Not working with Ubuntu 20.04. focal

### ISSUE THREAD

**Issue by didiatworkz** [tradebyte/paci#25]
Hello team,

Problem:
The installation fails if you want to install paci in Ubuntu 20.04.
```bash
Requirement already satisfied: pylint==1.6.5 in ./.local/lib/python3.8/site-packages (from -r /tmp/requirements.txt (line 1)) (1.6.5)
Collecting ipython==5.2.0
  Using cached ipython-5.2.0-py3-none-any.whl (749 kB)
Requirement already satisfied: docopt==0.6.2 in ./.local/lib/python3.8/site-packages (from -r /tmp/requirements.txt (line 3)) (0.6.2)
Collecting better_exceptions==0.1.5
  Using cached better_exceptions-0.1.5.tar.gz (3.6 kB)
Collecting ruamel.yaml==0.14.2
  Using cached ruamel.yaml-0.14.2.tar.gz (240 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9qp7xrix/ruamel.yaml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9qp7xrix/ruamel.yaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9qp7xrix/ruamel.yaml/pip-egg-info
         cwd: /tmp/pip-install-9qp7xrix/ruamel.yaml/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9qp7xrix/ruamel.yaml/setup.py", line 171, in <module>
        pkg_data = _package_data(__file__.replace('setup.py', '__init__.py'))
      File "/tmp/pip-install-9qp7xrix/ruamel.yaml/setup.py", line 150, in _package_data
        data = literal_eval(u''.join(lines))
      File "/tmp/pip-install-9qp7xrix/ruamel.yaml/setup.py", line 122, in literal_eval
        return _convert(node_or_string)
      File "/tmp/pip-install-9qp7xrix/ruamel.yaml/setup.py", line 69, in _convert
        if isinstance(node, (Str, Bytes)):
    NameError: name 'Str' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

Solution:
Update all requirements. In special `ruamel.yaml==0.14.2` to `ruamel.yaml==0.16.12`
Please check if newer requirements work and update the repo

Best,
Philipp Hörauf

**Comment by niklas-heer** [comment]
We still have to release it to pypi, then this issue should be fixed.

**Comment by niklas-heer** [comment]
@didiatworkz we released a new version which should fix this issue.

https://pypi.org/project/paci/1.10.3/

Just update your installed paci with: `pip3 install --upgrade paci`
